version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: '2g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: '2g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  search-module:
      image: eridazdocker/selenium-docker
      depends_on:
        - chrome
        - firefox
      environment:
        - BROWSER=chrome
        - HUB_HOST=hub
        - PORT=4444
        - MODULE=search-module.xml
      volumes:
        - test-search-data:/usr/share/udemy/test-output
  book-flight-module:
      image: eridazdocker/selenium-docker
      depends_on:
        - chrome
        - firefox
      environment:
        - BROWSER=firefox
        - HUB_HOST=hub
        - PORT=4444
        - MODULE=book-flight-module.xml
      volumes:
        - test-book-data:/usr/share/udemy/test-output
  checking-grid-status:
      image: bash
      depends_on:
        - chrome
        - firefox
      entrypoint: bash -c '
        echo "Starting Selenium Grid services..."
        docker-compose up -d hub chrome firefox
        
        echo "Installing jq and curl..."
        docker-compose exec -T bash bash -c 'apt-get update && apt-get install -y jq curl'

        echo "Waiting for Selenium Grid to be ready..."
        SELENIUM_READY=false
        while [[ "$SELENIUM_READY" != "true" ]]; do
          SELENIUM_READY=$(docker-compose exec -T hub curl -s http://hub:4444/wd/hub/status | jq -r .value.ready)
          sleep 1
        done

        echo "Selenium Grid is ready. Starting search-module and book-flight-module services..."
        docker-compose up -d search-module

        echo "Search module test completed"

        sleep 10

        echo "starting book-flight-module-tests"

        docker-compose up -d book-flight-module
        sleep 30

        echo "Script execution completed."

        exit 0'

volumes:
  test-search-data:
  test-book-data:
